// Mocks generated by Mockito 5.4.6 from annotations
// in bird_watching_mobile/test/screens/cache_management_property_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i4;

import 'package:bird_watching_mobile/data/repositories/photo_repository.dart'
    as _i8;
import 'package:bird_watching_mobile/data/services/api_service.dart' as _i5;
import 'package:bird_watching_mobile/data/services/local_database.dart' as _i7;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_2 extends _i1.SmartFake implements _i4.File {
  _FakeFile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
    Invocation.method(#setAuthToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuthToken() => super.noSuchMethod(
    Invocation.method(#clearAuthToken, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i2.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParams,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParams: queryParams, #options: options},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParams: queryParams, #options: options},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> post(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParams,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {#data: data, #queryParams: queryParams, #options: options},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {#data: data, #queryParams: queryParams, #options: options},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> put(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParams,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {#data: data, #queryParams: queryParams, #options: options},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {#data: data, #queryParams: queryParams, #options: options},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> delete(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParams,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {#data: data, #queryParams: queryParams, #options: options},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {#data: data, #queryParams: queryParams, #options: options},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> uploadFile(
    String? path,
    _i4.File? file, {
    String? fieldName = 'file',
    Map<String, dynamic>? additionalData,
    _i2.ProgressCallback? onSendProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [path, file],
              {
                #fieldName: fieldName,
                #additionalData: additionalData,
                #onSendProgress: onSendProgress,
              },
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #uploadFile,
                  [path, file],
                  {
                    #fieldName: fieldName,
                    #additionalData: additionalData,
                    #onSendProgress: onSendProgress,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LocalDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDatabase extends _i1.Mock implements _i7.LocalDatabase {
  MockLocalDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i3.Database>);

  @override
  void clearQueryCache() => super.noSuchMethod(
    Invocation.method(#clearQueryCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> insertObservation(
    Map<String, dynamic>? observation, {
    bool? pendingSync = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insertObservation,
              [observation],
              {#pendingSync: pendingSync},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> insertObservationsBatch(
    List<Map<String, dynamic>>? observations, {
    bool? pendingSync = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #insertObservationsBatch,
              [observations],
              {#pendingSync: pendingSync},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getObservations({
    String? userId,
    bool? pendingSync,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getObservations, [], {
              #userId: userId,
              #pendingSync: pendingSync,
              #useCache: useCache,
            }),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getObservationsPaginated({
    String? userId,
    bool? pendingSync,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getObservationsPaginated, [], {
              #userId: userId,
              #pendingSync: pendingSync,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<Map<String, dynamic>?> getObservationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getObservationById, [id]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> updateObservation(Map<String, dynamic>? observation) =>
      (super.noSuchMethod(
            Invocation.method(#updateObservation, [observation]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateObservationsBatch(
    List<Map<String, dynamic>>? observations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateObservationsBatch, [observations]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteObservation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteObservation, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteObservationsBatch(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteObservationsBatch, [ids]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getPendingSyncObservations() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncObservations, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> markAsSynced(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSynced, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markAsSyncedBatch(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#markAsSyncedBatch, [ids]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> insertTrip(Map<String, dynamic>? trip) =>
      (super.noSuchMethod(
            Invocation.method(#insertTrip, [trip]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getTrips({String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getTrips, [], {#userId: userId}),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<Map<String, dynamic>?> getTripById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTripById, [id]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> updateTrip(Map<String, dynamic>? trip) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrip, [trip]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteTrip(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrip, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getDatabaseSize() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabaseSize, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [PhotoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoRepository extends _i1.Mock implements _i8.PhotoRepository {
  MockPhotoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> uploadPhoto(_i4.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [photo]),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadPhoto, [photo]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i4.File> compressPhoto(
    _i4.File? photo, {
    int? quality = 85,
    int? maxWidth,
    int? maxHeight,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #compressPhoto,
              [photo],
              {#quality: quality, #maxWidth: maxWidth, #maxHeight: maxHeight},
            ),
            returnValue: _i6.Future<_i4.File>.value(
              _FakeFile_2(
                this,
                Invocation.method(
                  #compressPhoto,
                  [photo],
                  {
                    #quality: quality,
                    #maxWidth: maxWidth,
                    #maxHeight: maxHeight,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.File>);

  @override
  _i6.Future<void> cachePhoto(String? url, _i4.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#cachePhoto, [url, photo]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.File?> getCachedPhoto(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPhoto, [url]),
            returnValue: _i6.Future<_i4.File?>.value(),
          )
          as _i6.Future<_i4.File?>);

  @override
  _i6.Future<void> clearPhotoCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearPhotoCache, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getCacheSize() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheSize, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<_i4.File?> downloadAndCachePhoto(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#downloadAndCachePhoto, [url]),
            returnValue: _i6.Future<_i4.File?>.value(),
          )
          as _i6.Future<_i4.File?>);

  @override
  _i6.Future<void> manageCacheSize() =>
      (super.noSuchMethod(
            Invocation.method(#manageCacheSize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
