// Mocks generated by Mockito 5.4.6 from annotations
// in bird_watching_mobile/test/screens/map_screen_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bird_watching_mobile/data/models/observation.dart' as _i2;
import 'package:bird_watching_mobile/data/repositories/observation_repository.dart'
    as _i5;
import 'package:bird_watching_mobile/data/services/gps_service.dart' as _i7;
import 'package:bird_watching_mobile/presentation/blocs/auth/auth_bloc.dart'
    as _i9;
import 'package:bird_watching_mobile/presentation/blocs/auth/auth_event.dart'
    as _i10;
import 'package:bird_watching_mobile/presentation/blocs/auth/auth_state.dart'
    as _i3;
import 'package:bird_watching_mobile/presentation/blocs/map/map_bloc.dart'
    as _i12;
import 'package:bird_watching_mobile/presentation/blocs/map/map_event.dart'
    as _i13;
import 'package:bird_watching_mobile/presentation/blocs/map/map_state.dart'
    as _i4;
import 'package:flutter_bloc/flutter_bloc.dart' as _i11;
import 'package:geolocator/geolocator.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeObservation_0 extends _i1.SmartFake implements _i2.Observation {
  _FakeObservation_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthState_1 extends _i1.SmartFake implements _i3.AuthState {
  _FakeAuthState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMapState_2 extends _i1.SmartFake implements _i4.MapState {
  _FakeMapState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ObservationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockObservationRepository extends _i1.Mock
    implements _i5.ObservationRepository {
  MockObservationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.Observation>> getObservations({
    bool? forceRefresh = false,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getObservations, [], {
              #forceRefresh: forceRefresh,
              #userId: userId,
            }),
            returnValue: _i6.Future<List<_i2.Observation>>.value(
              <_i2.Observation>[],
            ),
          )
          as _i6.Future<List<_i2.Observation>>);

  @override
  _i6.Future<_i2.Observation?> getObservationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getObservationById, [id]),
            returnValue: _i6.Future<_i2.Observation?>.value(),
          )
          as _i6.Future<_i2.Observation?>);

  @override
  _i6.Future<_i2.Observation> createObservation(_i2.Observation? observation) =>
      (super.noSuchMethod(
            Invocation.method(#createObservation, [observation]),
            returnValue: _i6.Future<_i2.Observation>.value(
              _FakeObservation_0(
                this,
                Invocation.method(#createObservation, [observation]),
              ),
            ),
          )
          as _i6.Future<_i2.Observation>);

  @override
  _i6.Future<_i2.Observation> updateObservation(_i2.Observation? observation) =>
      (super.noSuchMethod(
            Invocation.method(#updateObservation, [observation]),
            returnValue: _i6.Future<_i2.Observation>.value(
              _FakeObservation_0(
                this,
                Invocation.method(#updateObservation, [observation]),
              ),
            ),
          )
          as _i6.Future<_i2.Observation>);

  @override
  _i6.Future<void> deleteObservation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteObservation, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.Observation>> getPendingSyncObservations() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncObservations, []),
            returnValue: _i6.Future<List<_i2.Observation>>.value(
              <_i2.Observation>[],
            ),
          )
          as _i6.Future<List<_i2.Observation>>);

  @override
  _i6.Future<void> syncObservation(_i2.Observation? observation) =>
      (super.noSuchMethod(
            Invocation.method(#syncObservation, [observation]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.Observation>> searchObservations(
    String? query, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchObservations, [query], {#userId: userId}),
            returnValue: _i6.Future<List<_i2.Observation>>.value(
              <_i2.Observation>[],
            ),
          )
          as _i6.Future<List<_i2.Observation>>);

  @override
  _i6.Future<List<_i2.Observation>> filterByDateRange(
    DateTime? startDate,
    DateTime? endDate, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #filterByDateRange,
              [startDate, endDate],
              {#userId: userId},
            ),
            returnValue: _i6.Future<List<_i2.Observation>>.value(
              <_i2.Observation>[],
            ),
          )
          as _i6.Future<List<_i2.Observation>>);

  @override
  _i6.Future<List<_i2.Observation>> getSharedObservations({
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedObservations, [], {
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i6.Future<List<_i2.Observation>>.value(
              <_i2.Observation>[],
            ),
          )
          as _i6.Future<List<_i2.Observation>>);
}

/// A class which mocks [GpsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGpsService extends _i1.Mock implements _i7.GpsService {
  MockGpsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i8.Position?> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i6.Future<_i8.Position?>.value(),
          )
          as _i6.Future<_i8.Position?>);

  @override
  _i6.Future<_i8.Position?> getCurrentPositionWithAccuracy(
    _i8.LocationAccuracy? accuracy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPositionWithAccuracy, [accuracy]),
            returnValue: _i6.Future<_i8.Position?>.value(),
          )
          as _i6.Future<_i8.Position?>);

  @override
  _i6.Future<bool> isLocationServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationServiceEnabled, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i8.LocationPermission> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i6.Future<_i8.LocationPermission>.value(
              _i8.LocationPermission.denied,
            ),
          )
          as _i6.Future<_i8.LocationPermission>);

  @override
  _i6.Future<_i8.LocationPermission> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i6.Future<_i8.LocationPermission>.value(
              _i8.LocationPermission.denied,
            ),
          )
          as _i6.Future<_i8.LocationPermission>);

  @override
  _i6.Stream<_i8.Position> getPositionStream({
    _i8.LocationAccuracy? accuracy = _i8.LocationAccuracy.high,
    int? distanceFilter = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, [], {
              #accuracy: accuracy,
              #distanceFilter: distanceFilter,
            }),
            returnValue: _i6.Stream<_i8.Position>.empty(),
          )
          as _i6.Stream<_i8.Position>);

  @override
  bool isAccuracyAcceptable(_i8.Position? position) =>
      (super.noSuchMethod(
            Invocation.method(#isAccuracyAcceptable, [position]),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<_i8.Position?> getLastKnownPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getLastKnownPosition, []),
            returnValue: _i6.Future<_i8.Position?>.value(),
          )
          as _i6.Future<_i8.Position?>);

  @override
  double distanceBetween(
    double? startLatitude,
    double? startLongitude,
    double? endLatitude,
    double? endLongitude,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#distanceBetween, [
              startLatitude,
              startLongitude,
              endLatitude,
              endLongitude,
            ]),
            returnValue: 0.0,
          )
          as double);

  @override
  _i6.Future<bool> openLocationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettings, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i9.AuthBloc {
  MockAuthBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_1(this, Invocation.getter(#state)),
          )
          as _i3.AuthState);

  @override
  _i6.Stream<_i3.AuthState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i3.AuthState>.empty(),
          )
          as _i6.Stream<_i3.AuthState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i10.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i10.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.AuthState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i10.AuthEvent>(
    _i11.EventHandler<E, _i3.AuthState>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i11.Transition<_i10.AuthEvent, _i3.AuthState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i11.Change<_i3.AuthState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MapBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapBloc extends _i1.Mock implements _i12.MapBloc {
  MockMapBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MapState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMapState_2(this, Invocation.getter(#state)),
          )
          as _i4.MapState);

  @override
  _i6.Stream<_i4.MapState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.MapState>.empty(),
          )
          as _i6.Stream<_i4.MapState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i13.MapEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i13.MapEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.MapState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i13.MapEvent>(
    _i11.EventHandler<E, _i4.MapState>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i11.Transition<_i13.MapEvent, _i4.MapState>? transition) =>
      super.noSuchMethod(
        Invocation.method(#onTransition, [transition]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i11.Change<_i4.MapState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
