"""Add calendar integration tables

Revision ID: 916737912d0c
Revises: 277687f44262
Create Date: 2025-12-21 23:00:55.374382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '916737912d0c'
down_revision: Union[str, None] = '277687f44262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'OUTLOOK', name='calendarprovider'), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', 'EXPIRED', name='calendarconnectionstatus'), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_integration_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('suggestion_threshold', sa.Float(), nullable=False),
    sa.Column('excluded_calendars', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('excluded_keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('include_declined_events', sa.Boolean(), nullable=False),
    sa.Column('include_all_day_events', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attendees', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('organizer', sa.String(length=255), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('calendar_event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('suggested_title', sa.String(length=500), nullable=False),
    sa.Column('suggested_description', sa.Text(), nullable=True),
    sa.Column('suggested_category', sa.String(length=100), nullable=False),
    sa.Column('suggested_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activities', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.alter_column('activities', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('activities', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('activities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_activities_category'), table_name='activities')
    op.drop_index(op.f('idx_activities_search'), table_name='activities', postgresql_using='gin')
    op.drop_index(op.f('idx_activities_tags'), table_name='activities', postgresql_using='gin')
    op.drop_index(op.f('idx_activities_user_date'), table_name='activities')
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_date'), 'activities', ['date'], unique=False)
    op.drop_column('activities', 'metadata')
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('reports', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_reports_user_type'), table_name='reports')
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.alter_column('stories', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('stories', 'impact_metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('stories', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('stories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_stories_search'), table_name='stories', postgresql_using='gin')
    op.drop_index(op.f('idx_stories_user_status'), table_name='stories')
    op.create_index(op.f('ix_stories_created_at'), 'stories', ['created_at'], unique=False)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_cognito_user_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_cognito_user_id'), 'users', ['cognito_user_id'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_cognito_user_id'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_cognito_user_id_key'), 'users', ['cognito_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_stories_created_at'), table_name='stories')
    op.create_index(op.f('idx_stories_user_status'), 'stories', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_stories_search'), 'stories', [sa.literal_column("to_tsvector('english'::regconfig, (((((((title::text || ' '::text) || situation) || ' '::text) || task) || ' '::text) || action) || ' '::text) || result)")], unique=False, postgresql_using='gin')
    op.alter_column('stories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stories', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('stories', 'impact_metrics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('stories', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.create_index(op.f('idx_reports_user_type'), 'reports', ['user_id', 'report_type'], unique=False)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('reports', 'updated_at')
    op.add_column('activities', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_activities_date'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.create_index(op.f('idx_activities_user_date'), 'activities', ['user_id', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_activities_tags'), 'activities', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_activities_search'), 'activities', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_activities_category'), 'activities', ['category'], unique=False)
    op.alter_column('activities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('activities', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('activities', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('activities', 'metadata_json')
    op.drop_table('activity_suggestions')
    op.drop_table('calendar_events')
    op.drop_table('calendar_integration_settings')
    op.drop_table('calendar_connections')
    # ### end Alembic commands ###