"""
Sample country data for the Country Data API.
Provides comprehensive country information for all countries in the world.
Data includes all UN member states and some territories.
"""

from models.country import Country


_sample_countries = None

def get_sample_countries():
    """
    Returns a list of all countries in the world with realistic data.
    Covers all regions: Africa, Americas, Asia, Europe, and Oceania.
    Population data is approximate as of 2023-2024.
    """
    global _sample_countries
    if _sample_countries is None:
        _sample_countries = _create_countries()
    return _sample_countries

def _create_countries():
    """Create the list of countries (called only once)."""
    return [
        # AFRICA
        Country(name="Algeria", capital="Algiers", population=44700000, region="Africa", languages=["Arabic", "Berber"]),
        Country(name="Angola", capital="Luanda", population=35589000, region="Africa", languages=["Portuguese"]),
        Country(name="Benin", capital="Porto-Novo", population=13353000, region="Africa", languages=["French"]),
        Country(name="Botswana", capital="Gaborone", population=2630000, region="Africa", languages=["English", "Setswana"]),
        Country(name="Burkina Faso", capital="Ouagadougou", population=22673000, region="Africa", languages=["French"]),
        Country(name="Burundi", capital="Gitega", population=12889000, region="Africa", languages=["Kirundi", "French"]),
        Country(name="Cameroon", capital="Yaoundé", population=28648000, region="Africa", languages=["French", "English"]),
        Country(name="Cape Verde", capital="Praia", population=593000, region="Africa", languages=["Portuguese"]),
        Country(name="Central African Republic", capital="Bangui", population=5579000, region="Africa", languages=["French", "Sango"]),
        Country(name="Chad", capital="N'Djamena", population=17723000, region="Africa", languages=["French", "Arabic"]),
        Country(name="Comoros", capital="Moroni", population=837000, region="Africa", languages=["Comorian", "Arabic", "French"]),
        Country(name="Congo", capital="Brazzaville", population=5970000, region="Africa", languages=["French"]),
        Country(name="Democratic Republic of the Congo", capital="Kinshasa", population=99010000, region="Africa", languages=["French"]),
        Country(name="Djibouti", capital="Djibouti", population=1120000, region="Africa", languages=["French", "Arabic"]),
        Country(name="Egypt", capital="Cairo", population=110990000, region="Africa", languages=["Arabic"]),
        Country(name="Equatorial Guinea", capital="Malabo", population=1675000, region="Africa", languages=["Spanish", "French", "Portuguese"]),
        Country(name="Eritrea", capital="Asmara", population=3684000, region="Africa", languages=["Tigrinya", "Arabic", "English"]),
        Country(name="Eswatini", capital="Mbabane", population=1202000, region="Africa", languages=["English", "Swazi"]),
        Country(name="Ethiopia", capital="Addis Ababa", population=123379000, region="Africa", languages=["Amharic"]),
        Country(name="Gabon", capital="Libreville", population=2388000, region="Africa", languages=["French"]),
        Country(name="Gambia", capital="Banjul", population=2705000, region="Africa", languages=["English"]),
        Country(name="Ghana", capital="Accra", population=33476000, region="Africa", languages=["English"]),
        Country(name="Guinea", capital="Conakry", population=13859000, region="Africa", languages=["French"]),
        Country(name="Guinea-Bissau", capital="Bissau", population=2105000, region="Africa", languages=["Portuguese"]),
        Country(name="Ivory Coast", capital="Yamoussoukro", population=28874000, region="Africa", languages=["French"]),
        Country(name="Kenya", capital="Nairobi", population=54027000, region="Africa", languages=["Swahili", "English"]),
        Country(name="Lesotho", capital="Maseru", population=2306000, region="Africa", languages=["Sesotho", "English"]),
        Country(name="Liberia", capital="Monrovia", population=5305000, region="Africa", languages=["English"]),
        Country(name="Libya", capital="Tripoli", population=6812000, region="Africa", languages=["Arabic"]),
        Country(name="Madagascar", capital="Antananarivo", population=29611000, region="Africa", languages=["Malagasy", "French"]),
        Country(name="Malawi", capital="Lilongwe", population=20405000, region="Africa", languages=["English", "Chichewa"]),
        Country(name="Mali", capital="Bamako", population=22594000, region="Africa", languages=["French"]),
        Country(name="Mauritania", capital="Nouakchott", population=4736000, region="Africa", languages=["Arabic"]),
        Country(name="Mauritius", capital="Port Louis", population=1300000, region="Africa", languages=["English", "French"]),
        Country(name="Morocco", capital="Rabat", population=37458000, region="Africa", languages=["Arabic", "Berber"]),
        Country(name="Mozambique", capital="Maputo", population=32969000, region="Africa", languages=["Portuguese"]),
        Country(name="Namibia", capital="Windhoek", population=2567000, region="Africa", languages=["English"]),
        Country(name="Niger", capital="Niamey", population=26207000, region="Africa", languages=["French"]),
        Country(name="Nigeria", capital="Abuja", population=223804000, region="Africa", languages=["English"]),
        Country(name="Rwanda", capital="Kigali", population=13776000, region="Africa", languages=["Kinyarwanda", "French", "English"]),
        Country(name="São Tomé and Príncipe", capital="São Tomé", population=227000, region="Africa", languages=["Portuguese"]),
        Country(name="Senegal", capital="Dakar", population=17316000, region="Africa", languages=["French"]),
        Country(name="Seychelles", capital="Victoria", population=107000, region="Africa", languages=["English", "French", "Seychellois Creole"]),
        Country(name="Sierra Leone", capital="Freetown", population=8605000, region="Africa", languages=["English"]),
        Country(name="Somalia", capital="Mogadishu", population=17597000, region="Africa", languages=["Somali", "Arabic"]),
        Country(name="South Africa", capital="Pretoria", population=60142000, region="Africa", languages=["Zulu", "Xhosa", "Afrikaans", "English"]),
        Country(name="South Sudan", capital="Juba", population=11088000, region="Africa", languages=["English"]),
        Country(name="Sudan", capital="Khartoum", population=46874000, region="Africa", languages=["Arabic", "English"]),
        Country(name="Tanzania", capital="Dodoma", population=65498000, region="Africa", languages=["Swahili", "English"]),
        Country(name="Togo", capital="Lomé", population=8848000, region="Africa", languages=["French"]),
        Country(name="Tunisia", capital="Tunis", population=12356000, region="Africa", languages=["Arabic"]),
        Country(name="Uganda", capital="Kampala", population=47249000, region="Africa", languages=["English", "Swahili"]),
        Country(name="Zambia", capital="Lusaka", population=20017000, region="Africa", languages=["English"]),
        Country(name="Zimbabwe", capital="Harare", population=16320000, region="Africa", languages=["English", "Shona", "Ndebele"]),

        # AMERICAS
        Country(name="Antigua and Barbuda", capital="St. John's", population=93000, region="Americas", languages=["English"]),
        Country(name="Argentina", capital="Buenos Aires", population=45510000, region="Americas", languages=["Spanish"]),
        Country(name="Bahamas", capital="Nassau", population=407000, region="Americas", languages=["English"]),
        Country(name="Barbados", capital="Bridgetown", population=281000, region="Americas", languages=["English"]),
        Country(name="Belize", capital="Belmopan", population=405000, region="Americas", languages=["English"]),
        Country(name="Bolivia", capital="Sucre", population=12224000, region="Americas", languages=["Spanish", "Quechua", "Aymara"]),
        Country(name="Brazil", capital="Brasília", population=215313000, region="Americas", languages=["Portuguese"]),
        Country(name="Canada", capital="Ottawa", population=38930000, region="Americas", languages=["English", "French"]),
        Country(name="Chile", capital="Santiago", population=19603000, region="Americas", languages=["Spanish"]),
        Country(name="Colombia", capital="Bogotá", population=51874000, region="Americas", languages=["Spanish"]),
        Country(name="Costa Rica", capital="San José", population=5180000, region="Americas", languages=["Spanish"]),
        Country(name="Cuba", capital="Havana", population=11212000, region="Americas", languages=["Spanish"]),
        Country(name="Dominica", capital="Roseau", population=72000, region="Americas", languages=["English"]),
        Country(name="Dominican Republic", capital="Santo Domingo", population=11228000, region="Americas", languages=["Spanish"]),
        Country(name="Ecuador", capital="Quito", population=18001000, region="Americas", languages=["Spanish"]),
        Country(name="El Salvador", capital="San Salvador", population=6336000, region="Americas", languages=["Spanish"]),
        Country(name="Grenada", capital="St. George's", population=125000, region="Americas", languages=["English"]),
        Country(name="Guatemala", capital="Guatemala City", population=17109000, region="Americas", languages=["Spanish"]),
        Country(name="Guyana", capital="Georgetown", population=808000, region="Americas", languages=["English"]),
        Country(name="Haiti", capital="Port-au-Prince", population=11584000, region="Americas", languages=["French", "Haitian Creole"]),
        Country(name="Honduras", capital="Tegucigalpa", population=10433000, region="Americas", languages=["Spanish"]),
        Country(name="Jamaica", capital="Kingston", population=2828000, region="Americas", languages=["English"]),
        Country(name="Mexico", capital="Mexico City", population=128932000, region="Americas", languages=["Spanish"]),
        Country(name="Nicaragua", capital="Managua", population=6948000, region="Americas", languages=["Spanish"]),
        Country(name="Panama", capital="Panama City", population=4408000, region="Americas", languages=["Spanish"]),
        Country(name="Paraguay", capital="Asunción", population=6780000, region="Americas", languages=["Spanish", "Guaraní"]),
        Country(name="Peru", capital="Lima", population=34352000, region="Americas", languages=["Spanish", "Quechua", "Aymara"]),
        Country(name="Saint Kitts and Nevis", capital="Basseterre", population=47000, region="Americas", languages=["English"]),
        Country(name="Saint Lucia", capital="Castries", population=180000, region="Americas", languages=["English"]),
        Country(name="Saint Vincent and the Grenadines", capital="Kingstown", population=104000, region="Americas", languages=["English"]),
        Country(name="Suriname", capital="Paramaribo", population=618000, region="Americas", languages=["Dutch"]),
        Country(name="Trinidad and Tobago", capital="Port of Spain", population=1531000, region="Americas", languages=["English"]),
        Country(name="United States", capital="Washington, D.C.", population=339996000, region="Americas", languages=["English"]),
        Country(name="Uruguay", capital="Montevideo", population=3423000, region="Americas", languages=["Spanish"]),
        Country(name="Venezuela", capital="Caracas", population=28302000, region="Americas", languages=["Spanish"]),

        # ASIA
        Country(name="Afghanistan", capital="Kabul", population=41128000, region="Asia", languages=["Pashto", "Dari"]),
        Country(name="Armenia", capital="Yerevan", population=2777000, region="Asia", languages=["Armenian"]),
        Country(name="Azerbaijan", capital="Baku", population=10412000, region="Asia", languages=["Azerbaijani"]),
        Country(name="Bahrain", capital="Manama", population=1472000, region="Asia", languages=["Arabic"]),
        Country(name="Bangladesh", capital="Dhaka", population=171186000, region="Asia", languages=["Bengali"]),
        Country(name="Bhutan", capital="Thimphu", population=782000, region="Asia", languages=["Dzongkha"]),
        Country(name="Brunei", capital="Bandar Seri Begawan", population=449000, region="Asia", languages=["Malay"]),
        Country(name="Cambodia", capital="Phnom Penh", population=16767000, region="Asia", languages=["Khmer"]),
        Country(name="China", capital="Beijing", population=1425672000, region="Asia", languages=["Mandarin Chinese"]),
        Country(name="Cyprus", capital="Nicosia", population=1251000, region="Asia", languages=["Greek", "Turkish"]),
        Country(name="Georgia", capital="Tbilisi", population=3728000, region="Asia", languages=["Georgian"]),
        Country(name="India", capital="New Delhi", population=1428627000, region="Asia", languages=["Hindi", "English"]),
        Country(name="Indonesia", capital="Jakarta", population=277534000, region="Asia", languages=["Indonesian"]),
        Country(name="Iran", capital="Tehran", population=88551000, region="Asia", languages=["Persian"]),
        Country(name="Iraq", capital="Baghdad", population=44496000, region="Asia", languages=["Arabic", "Kurdish"]),
        Country(name="Israel", capital="Jerusalem", population=9557000, region="Asia", languages=["Hebrew", "Arabic"]),
        Country(name="Japan", capital="Tokyo", population=123295000, region="Asia", languages=["Japanese"]),
        Country(name="Jordan", capital="Amman", population=11285000, region="Asia", languages=["Arabic"]),
        Country(name="Kazakhstan", capital="Astana", population=19622000, region="Asia", languages=["Kazakh", "Russian"]),
        Country(name="Kuwait", capital="Kuwait City", population=4310000, region="Asia", languages=["Arabic"]),
        Country(name="Kyrgyzstan", capital="Bishkek", population=6975000, region="Asia", languages=["Kyrgyz", "Russian"]),
        Country(name="Laos", capital="Vientiane", population=7529000, region="Asia", languages=["Lao"]),
        Country(name="Lebanon", capital="Beirut", population=5490000, region="Asia", languages=["Arabic"]),
        Country(name="Malaysia", capital="Kuala Lumpur", population=34308000, region="Asia", languages=["Malay"]),
        Country(name="Maldives", capital="Malé", population=521000, region="Asia", languages=["Dhivehi"]),
        Country(name="Mongolia", capital="Ulaanbaatar", population=3398000, region="Asia", languages=["Mongolian"]),
        Country(name="Myanmar", capital="Naypyidaw", population=54577000, region="Asia", languages=["Burmese"]),
        Country(name="Nepal", capital="Kathmandu", population=30548000, region="Asia", languages=["Nepali"]),
        Country(name="North Korea", capital="Pyongyang", population=26069000, region="Asia", languages=["Korean"]),
        Country(name="Oman", capital="Muscat", population=4576000, region="Asia", languages=["Arabic"]),
        Country(name="Pakistan", capital="Islamabad", population=235825000, region="Asia", languages=["Urdu", "English"]),
        Country(name="Palestine", capital="Ramallah", population=5371000, region="Asia", languages=["Arabic"]),
        Country(name="Philippines", capital="Manila", population=115560000, region="Asia", languages=["Filipino", "English"]),
        Country(name="Qatar", capital="Doha", population=2688000, region="Asia", languages=["Arabic"]),
        Country(name="Saudi Arabia", capital="Riyadh", population=36408000, region="Asia", languages=["Arabic"]),
        Country(name="Singapore", capital="Singapore", population=5454000, region="Asia", languages=["English", "Malay", "Mandarin", "Tamil"]),
        Country(name="South Korea", capital="Seoul", population=51784000, region="Asia", languages=["Korean"]),
        Country(name="Sri Lanka", capital="Sri Jayawardenepura Kotte", population=22181000, region="Asia", languages=["Sinhala", "Tamil"]),
        Country(name="Syria", capital="Damascus", population=22125000, region="Asia", languages=["Arabic"]),
        Country(name="Tajikistan", capital="Dushanbe", population=10077000, region="Asia", languages=["Tajik"]),
        Country(name="Thailand", capital="Bangkok", population=71801000, region="Asia", languages=["Thai"]),
        Country(name="Timor-Leste", capital="Dili", population=1341000, region="Asia", languages=["Tetum", "Portuguese"]),
        Country(name="Turkey", capital="Ankara", population=85816000, region="Asia", languages=["Turkish"]),
        Country(name="Turkmenistan", capital="Ashgabat", population=6431000, region="Asia", languages=["Turkmen"]),
        Country(name="United Arab Emirates", capital="Abu Dhabi", population=9441000, region="Asia", languages=["Arabic"]),
        Country(name="Uzbekistan", capital="Tashkent", population=35164000, region="Asia", languages=["Uzbek"]),
        Country(name="Vietnam", capital="Hanoi", population=98186000, region="Asia", languages=["Vietnamese"]),
        Country(name="Yemen", capital="Sana'a", population=33697000, region="Asia", languages=["Arabic"]),

        # EUROPE
        Country(name="Albania", capital="Tirana", population=2761000, region="Europe", languages=["Albanian"]),
        Country(name="Andorra", capital="Andorra la Vella", population=80000, region="Europe", languages=["Catalan"]),
        Country(name="Austria", capital="Vienna", population=9042000, region="Europe", languages=["German"]),
        Country(name="Belarus", capital="Minsk", population=9056000, region="Europe", languages=["Belarusian", "Russian"]),
        Country(name="Belgium", capital="Brussels", population=11655000, region="Europe", languages=["Dutch", "French", "German"]),
        Country(name="Bosnia and Herzegovina", capital="Sarajevo", population=3210000, region="Europe", languages=["Bosnian", "Croatian", "Serbian"]),
        Country(name="Bulgaria", capital="Sofia", population=6447000, region="Europe", languages=["Bulgarian"]),
        Country(name="Croatia", capital="Zagreb", population=3855000, region="Europe", languages=["Croatian"]),
        Country(name="Czech Republic", capital="Prague", population=10495000, region="Europe", languages=["Czech"]),
        Country(name="Denmark", capital="Copenhagen", population=5910000, region="Europe", languages=["Danish"]),
        Country(name="Estonia", capital="Tallinn", population=1365000, region="Europe", languages=["Estonian"]),
        Country(name="Finland", capital="Helsinki", population=5545000, region="Europe", languages=["Finnish", "Swedish"]),
        Country(name="France", capital="Paris", population=64756000, region="Europe", languages=["French"]),
        Country(name="Germany", capital="Berlin", population=83294000, region="Europe", languages=["German"]),
        Country(name="Greece", capital="Athens", population=10341000, region="Europe", languages=["Greek"]),
        Country(name="Hungary", capital="Budapest", population=9597000, region="Europe", languages=["Hungarian"]),
        Country(name="Iceland", capital="Reykjavik", population=375000, region="Europe", languages=["Icelandic"]),
        Country(name="Ireland", capital="Dublin", population=5127000, region="Europe", languages=["Irish", "English"]),
        Country(name="Italy", capital="Rome", population=58761000, region="Europe", languages=["Italian"]),
        Country(name="Kosovo", capital="Pristina", population=1775000, region="Europe", languages=["Albanian", "Serbian"]),
        Country(name="Latvia", capital="Riga", population=1830000, region="Europe", languages=["Latvian"]),
        Country(name="Liechtenstein", capital="Vaduz", population=39000, region="Europe", languages=["German"]),
        Country(name="Lithuania", capital="Vilnius", population=2718000, region="Europe", languages=["Lithuanian"]),
        Country(name="Luxembourg", capital="Luxembourg", population=654000, region="Europe", languages=["Luxembourgish", "French", "German"]),
        Country(name="Malta", capital="Valletta", population=535000, region="Europe", languages=["Maltese", "English"]),
        Country(name="Moldova", capital="Chișinău", population=2512000, region="Europe", languages=["Romanian"]),
        Country(name="Monaco", capital="Monaco", population=36000, region="Europe", languages=["French"]),
        Country(name="Montenegro", capital="Podgorica", population=616000, region="Europe", languages=["Montenegrin"]),
        Country(name="Netherlands", capital="Amsterdam", population=17618000, region="Europe", languages=["Dutch"]),
        Country(name="North Macedonia", capital="Skopje", population=2085000, region="Europe", languages=["Macedonian"]),
        Country(name="Norway", capital="Oslo", population=5488000, region="Europe", languages=["Norwegian"]),
        Country(name="Poland", capital="Warsaw", population=36822000, region="Europe", languages=["Polish"]),
        Country(name="Portugal", capital="Lisbon", population=10467000, region="Europe", languages=["Portuguese"]),
        Country(name="Romania", capital="Bucharest", population=19054000, region="Europe", languages=["Romanian"]),
        Country(name="Russia", capital="Moscow", population=144444000, region="Europe", languages=["Russian"]),
        Country(name="San Marino", capital="San Marino", population=34000, region="Europe", languages=["Italian"]),
        Country(name="Serbia", capital="Belgrade", population=6664000, region="Europe", languages=["Serbian"]),
        Country(name="Slovakia", capital="Bratislava", population=5426000, region="Europe", languages=["Slovak"]),
        Country(name="Slovenia", capital="Ljubljana", population=2119000, region="Europe", languages=["Slovenian"]),
        Country(name="Spain", capital="Madrid", population=47616000, region="Europe", languages=["Spanish"]),
        Country(name="Sweden", capital="Stockholm", population=10521000, region="Europe", languages=["Swedish"]),
        Country(name="Switzerland", capital="Bern", population=8796000, region="Europe", languages=["German", "French", "Italian", "Romansh"]),
        Country(name="Ukraine", capital="Kyiv", population=36745000, region="Europe", languages=["Ukrainian"]),
        Country(name="United Kingdom", capital="London", population=67736000, region="Europe", languages=["English"]),
        Country(name="Vatican City", capital="Vatican City", population=825, region="Europe", languages=["Italian", "Latin"]),

        # OCEANIA
        Country(name="Australia", capital="Canberra", population=26439000, region="Oceania", languages=["English"]),
        Country(name="Fiji", capital="Suva", population=929000, region="Oceania", languages=["English", "Fijian", "Hindi"]),
        Country(name="Kiribati", capital="Tarawa", population=131000, region="Oceania", languages=["English", "Gilbertese"]),
        Country(name="Marshall Islands", capital="Majuro", population=42000, region="Oceania", languages=["Marshallese", "English"]),
        Country(name="Micronesia", capital="Palikir", population=115000, region="Oceania", languages=["English"]),
        Country(name="Nauru", capital="Yaren", population=13000, region="Oceania", languages=["Nauruan", "English"]),
        Country(name="New Zealand", capital="Wellington", population=5228000, region="Oceania", languages=["English", "Māori"]),
        Country(name="Palau", capital="Ngerulmud", population=18000, region="Oceania", languages=["Palauan", "English"]),
        Country(name="Papua New Guinea", capital="Port Moresby", population=10142000, region="Oceania", languages=["English", "Tok Pisin", "Hiri Motu"]),
        Country(name="Samoa", capital="Apia", population=222000, region="Oceania", languages=["Samoan", "English"]),
        Country(name="Solomon Islands", capital="Honiara", population=724000, region="Oceania", languages=["English"]),
        Country(name="Tonga", capital="Nuku'alofa", population=107000, region="Oceania", languages=["Tongan", "English"]),
        Country(name="Tuvalu", capital="Funafuti", population=12000, region="Oceania", languages=["Tuvaluan", "English"]),
        Country(name="Vanuatu", capital="Port Vila", population=327000, region="Oceania", languages=["Bislama", "English", "French"]),
    ]
