use crate::models::Country;

pub fn get_sample_countries() -> Vec<Country> {
    vec![
        Country {
            name: "France".to_string(),
            capital: "Paris".to_string(),
            population: 67391582,
            region: "Europe".to_string(),
            languages: vec!["French".to_string()],
        },
        Country {
            name: "Germany".to_string(),
            capital: "Berlin".to_string(),
            population: 83240525,
            region: "Europe".to_string(),
            languages: vec!["German".to_string()],
        },
        Country {
            name: "Spain".to_string(),
            capital: "Madrid".to_string(),
            population: 47351567,
            region: "Europe".to_string(),
            languages: vec!["Spanish".to_string()],
        },
        Country {
            name: "Italy".to_string(),
            capital: "Rome".to_string(),
            population: 60367477,
            region: "Europe".to_string(),
            languages: vec!["Italian".to_string()],
        },
        Country {
            name: "United Kingdom".to_string(),
            capital: "London".to_string(),
            population: 67886011,
            region: "Europe".to_string(),
            languages: vec!["English".to_string(), "Welsh".to_string(), "Scottish Gaelic".to_string()],
        },
        Country {
            name: "Japan".to_string(),
            capital: "Tokyo".to_string(),
            population: 125836021,
            region: "Asia".to_string(),
            languages: vec!["Japanese".to_string()],
        },
        Country {
            name: "China".to_string(),
            capital: "Beijing".to_string(),
            population: 1439323776,
            region: "Asia".to_string(),
            languages: vec!["Mandarin".to_string()],
        },
        Country {
            name: "India".to_string(),
            capital: "New Delhi".to_string(),
            population: 1380004385,
            region: "Asia".to_string(),
            languages: vec!["Hindi".to_string(), "English".to_string()],
        },
        Country {
            name: "Thailand".to_string(),
            capital: "Bangkok".to_string(),
            population: 69799978,
            region: "Asia".to_string(),
            languages: vec!["Thai".to_string()],
        },
        Country {
            name: "United States".to_string(),
            capital: "Washington, D.C.".to_string(),
            population: 331002651,
            region: "Americas".to_string(),
            languages: vec!["English".to_string(), "Spanish".to_string()],
        },
        Country {
            name: "Canada".to_string(),
            capital: "Ottawa".to_string(),
            population: 37742154,
            region: "Americas".to_string(),
            languages: vec!["English".to_string(), "French".to_string()],
        },
        Country {
            name: "Brazil".to_string(),
            capital: "Brasília".to_string(),
            population: 212559417,
            region: "Americas".to_string(),
            languages: vec!["Portuguese".to_string()],
        },
        Country {
            name: "Mexico".to_string(),
            capital: "Mexico City".to_string(),
            population: 128932753,
            region: "Americas".to_string(),
            languages: vec!["Spanish".to_string()],
        },
        Country {
            name: "Egypt".to_string(),
            capital: "Cairo".to_string(),
            population: 102334404,
            region: "Africa".to_string(),
            languages: vec!["Arabic".to_string()],
        },
        Country {
            name: "South Africa".to_string(),
            capital: "Pretoria".to_string(),
            population: 59308690,
            region: "Africa".to_string(),
            languages: vec!["Afrikaans".to_string(), "English".to_string(), "Zulu".to_string()],
        },
        Country {
            name: "Australia".to_string(),
            capital: "Canberra".to_string(),
            population: 25499884,
            region: "Oceania".to_string(),
            languages: vec!["English".to_string()],
        },
        Country {
            name: "New Zealand".to_string(),
            capital: "Wellington".to_string(),
            population: 4822233,
            region: "Oceania".to_string(),
            languages: vec!["English".to_string(), "Māori".to_string()],
        },
    ]
}
