// Total countries: 196
use crate::models::Country;

pub fn get_sample_countries() -> Vec<Country> {
    vec![
        Country { name: "Algeria".to_string(), capital: "Algiers".to_string(), population: 44700000, region: "Africa".to_string(), languages: vec!["Arabic".to_string(), "Berber".to_string()] },
        Country { name: "Angola".to_string(), capital: "Luanda".to_string(), population: 35589000, region: "Africa".to_string(), languages: vec!["Portuguese".to_string()] },
        Country { name: "Benin".to_string(), capital: "Porto-Novo".to_string(), population: 13353000, region: "Africa".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Botswana".to_string(), capital: "Gaborone".to_string(), population: 2630000, region: "Africa".to_string(), languages: vec!["English".to_string(), "Setswana".to_string()] },
        Country { name: "Burkina Faso".to_string(), capital: "Ouagadougou".to_string(), population: 22673000, region: "Africa".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Burundi".to_string(), capital: "Gitega".to_string(), population: 12889000, region: "Africa".to_string(), languages: vec!["Kirundi".to_string(), "French".to_string()] },
        Country { name: "Cameroon".to_string(), capital: "Yaoundé".to_string(), population: 28648000, region: "Africa".to_string(), languages: vec!["French".to_string(), "English".to_string()] },
        Country { name: "Cape Verde".to_string(), capital: "Praia".to_string(), population: 593000, region: "Africa".to_string(), languages: vec!["Portuguese".to_string()] },
        Country { name: "Central African Republic".to_string(), capital: "Bangui".to_string(), population: 5579000, region: "Africa".to_string(), languages: vec!["French".to_string(), "Sango".to_string()] },
        Country { name: "Chad".to_string(), capital: "N'Djamena".to_string(), population: 17723000, region: "Africa".to_string(), languages: vec!["French".to_string(), "Arabic".to_string()] },
        Country { name: "Comoros".to_string(), capital: "Moroni".to_string(), population: 837000, region: "Africa".to_string(), languages: vec!["Comorian".to_string(), "Arabic".to_string(), "French".to_string()] },
        Country { name: "Congo".to_string(), capital: "Brazzaville".to_string(), population: 5970000, region: "Africa".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Democratic Republic of the Congo".to_string(), capital: "Kinshasa".to_string(), population: 99010000, region: "Africa".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Djibouti".to_string(), capital: "Djibouti".to_string(), population: 1120000, region: "Africa".to_string(), languages: vec!["French".to_string(), "Arabic".to_string()] },
        Country { name: "Egypt".to_string(), capital: "Cairo".to_string(), population: 110990000, region: "Africa".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Equatorial Guinea".to_string(), capital: "Malabo".to_string(), population: 1675000, region: "Africa".to_string(), languages: vec!["Spanish".to_string(), "French".to_string(), "Portuguese".to_string()] },
        Country { name: "Eritrea".to_string(), capital: "Asmara".to_string(), population: 3684000, region: "Africa".to_string(), languages: vec!["Tigrinya".to_string(), "Arabic".to_string(), "English".to_string()] },
        Country { name: "Eswatini".to_string(), capital: "Mbabane".to_string(), population: 1202000, region: "Africa".to_string(), languages: vec!["English".to_string(), "Swazi".to_string()] },
        Country { name: "Ethiopia".to_string(), capital: "Addis Ababa".to_string(), population: 123379000, region: "Africa".to_string(), languages: vec!["Amharic".to_string()] },
        Country { name: "Gabon".to_string(), capital: "Libreville".to_string(), population: 2388000, region: "Africa".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Gambia".to_string(), capital: "Banjul".to_string(), population: 2705000, region: "Africa".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Ghana".to_string(), capital: "Accra".to_string(), population: 33476000, region: "Africa".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Guinea".to_string(), capital: "Conakry".to_string(), population: 13859000, region: "Africa".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Guinea-Bissau".to_string(), capital: "Bissau".to_string(), population: 2105000, region: "Africa".to_string(), languages: vec!["Portuguese".to_string()] },
        Country { name: "Ivory Coast".to_string(), capital: "Yamoussoukro".to_string(), population: 28874000, region: "Africa".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Kenya".to_string(), capital: "Nairobi".to_string(), population: 54027000, region: "Africa".to_string(), languages: vec!["Swahili".to_string(), "English".to_string()] },
        Country { name: "Lesotho".to_string(), capital: "Maseru".to_string(), population: 2306000, region: "Africa".to_string(), languages: vec!["Sesotho".to_string(), "English".to_string()] },
        Country { name: "Liberia".to_string(), capital: "Monrovia".to_string(), population: 5305000, region: "Africa".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Libya".to_string(), capital: "Tripoli".to_string(), population: 6812000, region: "Africa".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Madagascar".to_string(), capital: "Antananarivo".to_string(), population: 29611000, region: "Africa".to_string(), languages: vec!["Malagasy".to_string(), "French".to_string()] },
        Country { name: "Malawi".to_string(), capital: "Lilongwe".to_string(), population: 20405000, region: "Africa".to_string(), languages: vec!["English".to_string(), "Chichewa".to_string()] },
        Country { name: "Mali".to_string(), capital: "Bamako".to_string(), population: 22594000, region: "Africa".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Mauritania".to_string(), capital: "Nouakchott".to_string(), population: 4736000, region: "Africa".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Mauritius".to_string(), capital: "Port Louis".to_string(), population: 1300000, region: "Africa".to_string(), languages: vec!["English".to_string(), "French".to_string()] },
        Country { name: "Morocco".to_string(), capital: "Rabat".to_string(), population: 37458000, region: "Africa".to_string(), languages: vec!["Arabic".to_string(), "Berber".to_string()] },
        Country { name: "Mozambique".to_string(), capital: "Maputo".to_string(), population: 32969000, region: "Africa".to_string(), languages: vec!["Portuguese".to_string()] },
        Country { name: "Namibia".to_string(), capital: "Windhoek".to_string(), population: 2567000, region: "Africa".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Niger".to_string(), capital: "Niamey".to_string(), population: 26207000, region: "Africa".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Nigeria".to_string(), capital: "Abuja".to_string(), population: 223804000, region: "Africa".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Rwanda".to_string(), capital: "Kigali".to_string(), population: 13776000, region: "Africa".to_string(), languages: vec!["Kinyarwanda".to_string(), "French".to_string(), "English".to_string()] },
        Country { name: "São Tomé and Príncipe".to_string(), capital: "São Tomé".to_string(), population: 227000, region: "Africa".to_string(), languages: vec!["Portuguese".to_string()] },
        Country { name: "Senegal".to_string(), capital: "Dakar".to_string(), population: 17316000, region: "Africa".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Seychelles".to_string(), capital: "Victoria".to_string(), population: 107000, region: "Africa".to_string(), languages: vec!["English".to_string(), "French".to_string(), "Seychellois Creole".to_string()] },
        Country { name: "Sierra Leone".to_string(), capital: "Freetown".to_string(), population: 8605000, region: "Africa".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Somalia".to_string(), capital: "Mogadishu".to_string(), population: 17597000, region: "Africa".to_string(), languages: vec!["Somali".to_string(), "Arabic".to_string()] },
        Country { name: "South Africa".to_string(), capital: "Pretoria".to_string(), population: 60142000, region: "Africa".to_string(), languages: vec!["Zulu".to_string(), "Xhosa".to_string(), "Afrikaans".to_string(), "English".to_string()] },
        Country { name: "South Sudan".to_string(), capital: "Juba".to_string(), population: 11088000, region: "Africa".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Sudan".to_string(), capital: "Khartoum".to_string(), population: 46874000, region: "Africa".to_string(), languages: vec!["Arabic".to_string(), "English".to_string()] },
        Country { name: "Tanzania".to_string(), capital: "Dodoma".to_string(), population: 65498000, region: "Africa".to_string(), languages: vec!["Swahili".to_string(), "English".to_string()] },
        Country { name: "Togo".to_string(), capital: "Lomé".to_string(), population: 8848000, region: "Africa".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Tunisia".to_string(), capital: "Tunis".to_string(), population: 12356000, region: "Africa".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Uganda".to_string(), capital: "Kampala".to_string(), population: 47249000, region: "Africa".to_string(), languages: vec!["English".to_string(), "Swahili".to_string()] },
        Country { name: "Zambia".to_string(), capital: "Lusaka".to_string(), population: 20017000, region: "Africa".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Zimbabwe".to_string(), capital: "Harare".to_string(), population: 16320000, region: "Africa".to_string(), languages: vec!["English".to_string(), "Shona".to_string(), "Ndebele".to_string()] },
        Country { name: "Antigua and Barbuda".to_string(), capital: "St. John's".to_string(), population: 93000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Argentina".to_string(), capital: "Buenos Aires".to_string(), population: 45510000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Bahamas".to_string(), capital: "Nassau".to_string(), population: 407000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Barbados".to_string(), capital: "Bridgetown".to_string(), population: 281000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Belize".to_string(), capital: "Belmopan".to_string(), population: 405000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Bolivia".to_string(), capital: "Sucre".to_string(), population: 12224000, region: "Americas".to_string(), languages: vec!["Spanish".to_string(), "Quechua".to_string(), "Aymara".to_string()] },
        Country { name: "Brazil".to_string(), capital: "Brasília".to_string(), population: 215313000, region: "Americas".to_string(), languages: vec!["Portuguese".to_string()] },
        Country { name: "Canada".to_string(), capital: "Ottawa".to_string(), population: 38930000, region: "Americas".to_string(), languages: vec!["English".to_string(), "French".to_string()] },
        Country { name: "Chile".to_string(), capital: "Santiago".to_string(), population: 19603000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Colombia".to_string(), capital: "Bogotá".to_string(), population: 51874000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Costa Rica".to_string(), capital: "San José".to_string(), population: 5180000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Cuba".to_string(), capital: "Havana".to_string(), population: 11212000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Dominica".to_string(), capital: "Roseau".to_string(), population: 72000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Dominican Republic".to_string(), capital: "Santo Domingo".to_string(), population: 11228000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Ecuador".to_string(), capital: "Quito".to_string(), population: 18001000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "El Salvador".to_string(), capital: "San Salvador".to_string(), population: 6336000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Grenada".to_string(), capital: "St. George's".to_string(), population: 125000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Guatemala".to_string(), capital: "Guatemala City".to_string(), population: 17109000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Guyana".to_string(), capital: "Georgetown".to_string(), population: 808000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Haiti".to_string(), capital: "Port-au-Prince".to_string(), population: 11584000, region: "Americas".to_string(), languages: vec!["French".to_string(), "Haitian Creole".to_string()] },
        Country { name: "Honduras".to_string(), capital: "Tegucigalpa".to_string(), population: 10433000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Jamaica".to_string(), capital: "Kingston".to_string(), population: 2828000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Mexico".to_string(), capital: "Mexico City".to_string(), population: 128932000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Nicaragua".to_string(), capital: "Managua".to_string(), population: 6948000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Panama".to_string(), capital: "Panama City".to_string(), population: 4408000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Paraguay".to_string(), capital: "Asunción".to_string(), population: 6780000, region: "Americas".to_string(), languages: vec!["Spanish".to_string(), "Guaraní".to_string()] },
        Country { name: "Peru".to_string(), capital: "Lima".to_string(), population: 34352000, region: "Americas".to_string(), languages: vec!["Spanish".to_string(), "Quechua".to_string(), "Aymara".to_string()] },
        Country { name: "Saint Kitts and Nevis".to_string(), capital: "Basseterre".to_string(), population: 47000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Saint Lucia".to_string(), capital: "Castries".to_string(), population: 180000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Saint Vincent and the Grenadines".to_string(), capital: "Kingstown".to_string(), population: 104000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Suriname".to_string(), capital: "Paramaribo".to_string(), population: 618000, region: "Americas".to_string(), languages: vec!["Dutch".to_string()] },
        Country { name: "Trinidad and Tobago".to_string(), capital: "Port of Spain".to_string(), population: 1531000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "United States".to_string(), capital: "Washington, D.C.".to_string(), population: 339996000, region: "Americas".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Uruguay".to_string(), capital: "Montevideo".to_string(), population: 3423000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Venezuela".to_string(), capital: "Caracas".to_string(), population: 28302000, region: "Americas".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Afghanistan".to_string(), capital: "Kabul".to_string(), population: 41128000, region: "Asia".to_string(), languages: vec!["Pashto".to_string(), "Dari".to_string()] },
        Country { name: "Armenia".to_string(), capital: "Yerevan".to_string(), population: 2777000, region: "Asia".to_string(), languages: vec!["Armenian".to_string()] },
        Country { name: "Azerbaijan".to_string(), capital: "Baku".to_string(), population: 10412000, region: "Asia".to_string(), languages: vec!["Azerbaijani".to_string()] },
        Country { name: "Bahrain".to_string(), capital: "Manama".to_string(), population: 1472000, region: "Asia".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Bangladesh".to_string(), capital: "Dhaka".to_string(), population: 171186000, region: "Asia".to_string(), languages: vec!["Bengali".to_string()] },
        Country { name: "Bhutan".to_string(), capital: "Thimphu".to_string(), population: 782000, region: "Asia".to_string(), languages: vec!["Dzongkha".to_string()] },
        Country { name: "Brunei".to_string(), capital: "Bandar Seri Begawan".to_string(), population: 449000, region: "Asia".to_string(), languages: vec!["Malay".to_string()] },
        Country { name: "Cambodia".to_string(), capital: "Phnom Penh".to_string(), population: 16767000, region: "Asia".to_string(), languages: vec!["Khmer".to_string()] },
        Country { name: "China".to_string(), capital: "Beijing".to_string(), population: 1425672000, region: "Asia".to_string(), languages: vec!["Mandarin Chinese".to_string()] },
        Country { name: "Cyprus".to_string(), capital: "Nicosia".to_string(), population: 1251000, region: "Asia".to_string(), languages: vec!["Greek".to_string(), "Turkish".to_string()] },
        Country { name: "Georgia".to_string(), capital: "Tbilisi".to_string(), population: 3728000, region: "Asia".to_string(), languages: vec!["Georgian".to_string()] },
        Country { name: "India".to_string(), capital: "New Delhi".to_string(), population: 1428627000, region: "Asia".to_string(), languages: vec!["Hindi".to_string(), "English".to_string()] },
        Country { name: "Indonesia".to_string(), capital: "Jakarta".to_string(), population: 277534000, region: "Asia".to_string(), languages: vec!["Indonesian".to_string()] },
        Country { name: "Iran".to_string(), capital: "Tehran".to_string(), population: 88551000, region: "Asia".to_string(), languages: vec!["Persian".to_string()] },
        Country { name: "Iraq".to_string(), capital: "Baghdad".to_string(), population: 44496000, region: "Asia".to_string(), languages: vec!["Arabic".to_string(), "Kurdish".to_string()] },
        Country { name: "Israel".to_string(), capital: "Jerusalem".to_string(), population: 9557000, region: "Asia".to_string(), languages: vec!["Hebrew".to_string(), "Arabic".to_string()] },
        Country { name: "Japan".to_string(), capital: "Tokyo".to_string(), population: 123295000, region: "Asia".to_string(), languages: vec!["Japanese".to_string()] },
        Country { name: "Jordan".to_string(), capital: "Amman".to_string(), population: 11285000, region: "Asia".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Kazakhstan".to_string(), capital: "Astana".to_string(), population: 19622000, region: "Asia".to_string(), languages: vec!["Kazakh".to_string(), "Russian".to_string()] },
        Country { name: "Kuwait".to_string(), capital: "Kuwait City".to_string(), population: 4310000, region: "Asia".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Kyrgyzstan".to_string(), capital: "Bishkek".to_string(), population: 6975000, region: "Asia".to_string(), languages: vec!["Kyrgyz".to_string(), "Russian".to_string()] },
        Country { name: "Laos".to_string(), capital: "Vientiane".to_string(), population: 7529000, region: "Asia".to_string(), languages: vec!["Lao".to_string()] },
        Country { name: "Lebanon".to_string(), capital: "Beirut".to_string(), population: 5490000, region: "Asia".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Malaysia".to_string(), capital: "Kuala Lumpur".to_string(), population: 34308000, region: "Asia".to_string(), languages: vec!["Malay".to_string()] },
        Country { name: "Maldives".to_string(), capital: "Malé".to_string(), population: 521000, region: "Asia".to_string(), languages: vec!["Dhivehi".to_string()] },
        Country { name: "Mongolia".to_string(), capital: "Ulaanbaatar".to_string(), population: 3398000, region: "Asia".to_string(), languages: vec!["Mongolian".to_string()] },
        Country { name: "Myanmar".to_string(), capital: "Naypyidaw".to_string(), population: 54577000, region: "Asia".to_string(), languages: vec!["Burmese".to_string()] },
        Country { name: "Nepal".to_string(), capital: "Kathmandu".to_string(), population: 30548000, region: "Asia".to_string(), languages: vec!["Nepali".to_string()] },
        Country { name: "North Korea".to_string(), capital: "Pyongyang".to_string(), population: 26069000, region: "Asia".to_string(), languages: vec!["Korean".to_string()] },
        Country { name: "Oman".to_string(), capital: "Muscat".to_string(), population: 4576000, region: "Asia".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Pakistan".to_string(), capital: "Islamabad".to_string(), population: 235825000, region: "Asia".to_string(), languages: vec!["Urdu".to_string(), "English".to_string()] },
        Country { name: "Palestine".to_string(), capital: "Ramallah".to_string(), population: 5371000, region: "Asia".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Philippines".to_string(), capital: "Manila".to_string(), population: 115560000, region: "Asia".to_string(), languages: vec!["Filipino".to_string(), "English".to_string()] },
        Country { name: "Qatar".to_string(), capital: "Doha".to_string(), population: 2688000, region: "Asia".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Saudi Arabia".to_string(), capital: "Riyadh".to_string(), population: 36408000, region: "Asia".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Singapore".to_string(), capital: "Singapore".to_string(), population: 5454000, region: "Asia".to_string(), languages: vec!["English".to_string(), "Malay".to_string(), "Mandarin".to_string(), "Tamil".to_string()] },
        Country { name: "South Korea".to_string(), capital: "Seoul".to_string(), population: 51784000, region: "Asia".to_string(), languages: vec!["Korean".to_string()] },
        Country { name: "Sri Lanka".to_string(), capital: "Sri Jayawardenepura Kotte".to_string(), population: 22181000, region: "Asia".to_string(), languages: vec!["Sinhala".to_string(), "Tamil".to_string()] },
        Country { name: "Syria".to_string(), capital: "Damascus".to_string(), population: 22125000, region: "Asia".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Tajikistan".to_string(), capital: "Dushanbe".to_string(), population: 10077000, region: "Asia".to_string(), languages: vec!["Tajik".to_string()] },
        Country { name: "Thailand".to_string(), capital: "Bangkok".to_string(), population: 71801000, region: "Asia".to_string(), languages: vec!["Thai".to_string()] },
        Country { name: "Timor-Leste".to_string(), capital: "Dili".to_string(), population: 1341000, region: "Asia".to_string(), languages: vec!["Tetum".to_string(), "Portuguese".to_string()] },
        Country { name: "Turkey".to_string(), capital: "Ankara".to_string(), population: 85816000, region: "Asia".to_string(), languages: vec!["Turkish".to_string()] },
        Country { name: "Turkmenistan".to_string(), capital: "Ashgabat".to_string(), population: 6431000, region: "Asia".to_string(), languages: vec!["Turkmen".to_string()] },
        Country { name: "United Arab Emirates".to_string(), capital: "Abu Dhabi".to_string(), population: 9441000, region: "Asia".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Uzbekistan".to_string(), capital: "Tashkent".to_string(), population: 35164000, region: "Asia".to_string(), languages: vec!["Uzbek".to_string()] },
        Country { name: "Vietnam".to_string(), capital: "Hanoi".to_string(), population: 98186000, region: "Asia".to_string(), languages: vec!["Vietnamese".to_string()] },
        Country { name: "Yemen".to_string(), capital: "Sana'a".to_string(), population: 33697000, region: "Asia".to_string(), languages: vec!["Arabic".to_string()] },
        Country { name: "Albania".to_string(), capital: "Tirana".to_string(), population: 2761000, region: "Europe".to_string(), languages: vec!["Albanian".to_string()] },
        Country { name: "Andorra".to_string(), capital: "Andorra la Vella".to_string(), population: 80000, region: "Europe".to_string(), languages: vec!["Catalan".to_string()] },
        Country { name: "Austria".to_string(), capital: "Vienna".to_string(), population: 9042000, region: "Europe".to_string(), languages: vec!["German".to_string()] },
        Country { name: "Belarus".to_string(), capital: "Minsk".to_string(), population: 9056000, region: "Europe".to_string(), languages: vec!["Belarusian".to_string(), "Russian".to_string()] },
        Country { name: "Belgium".to_string(), capital: "Brussels".to_string(), population: 11655000, region: "Europe".to_string(), languages: vec!["Dutch".to_string(), "French".to_string(), "German".to_string()] },
        Country { name: "Bosnia and Herzegovina".to_string(), capital: "Sarajevo".to_string(), population: 3210000, region: "Europe".to_string(), languages: vec!["Bosnian".to_string(), "Croatian".to_string(), "Serbian".to_string()] },
        Country { name: "Bulgaria".to_string(), capital: "Sofia".to_string(), population: 6447000, region: "Europe".to_string(), languages: vec!["Bulgarian".to_string()] },
        Country { name: "Croatia".to_string(), capital: "Zagreb".to_string(), population: 3855000, region: "Europe".to_string(), languages: vec!["Croatian".to_string()] },
        Country { name: "Czech Republic".to_string(), capital: "Prague".to_string(), population: 10495000, region: "Europe".to_string(), languages: vec!["Czech".to_string()] },
        Country { name: "Denmark".to_string(), capital: "Copenhagen".to_string(), population: 5910000, region: "Europe".to_string(), languages: vec!["Danish".to_string()] },
        Country { name: "Estonia".to_string(), capital: "Tallinn".to_string(), population: 1365000, region: "Europe".to_string(), languages: vec!["Estonian".to_string()] },
        Country { name: "Finland".to_string(), capital: "Helsinki".to_string(), population: 5545000, region: "Europe".to_string(), languages: vec!["Finnish".to_string(), "Swedish".to_string()] },
        Country { name: "France".to_string(), capital: "Paris".to_string(), population: 64756000, region: "Europe".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Germany".to_string(), capital: "Berlin".to_string(), population: 83294000, region: "Europe".to_string(), languages: vec!["German".to_string()] },
        Country { name: "Greece".to_string(), capital: "Athens".to_string(), population: 10341000, region: "Europe".to_string(), languages: vec!["Greek".to_string()] },
        Country { name: "Hungary".to_string(), capital: "Budapest".to_string(), population: 9597000, region: "Europe".to_string(), languages: vec!["Hungarian".to_string()] },
        Country { name: "Iceland".to_string(), capital: "Reykjavik".to_string(), population: 375000, region: "Europe".to_string(), languages: vec!["Icelandic".to_string()] },
        Country { name: "Ireland".to_string(), capital: "Dublin".to_string(), population: 5127000, region: "Europe".to_string(), languages: vec!["Irish".to_string(), "English".to_string()] },
        Country { name: "Italy".to_string(), capital: "Rome".to_string(), population: 58761000, region: "Europe".to_string(), languages: vec!["Italian".to_string()] },
        Country { name: "Kosovo".to_string(), capital: "Pristina".to_string(), population: 1775000, region: "Europe".to_string(), languages: vec!["Albanian".to_string(), "Serbian".to_string()] },
        Country { name: "Latvia".to_string(), capital: "Riga".to_string(), population: 1830000, region: "Europe".to_string(), languages: vec!["Latvian".to_string()] },
        Country { name: "Liechtenstein".to_string(), capital: "Vaduz".to_string(), population: 39000, region: "Europe".to_string(), languages: vec!["German".to_string()] },
        Country { name: "Lithuania".to_string(), capital: "Vilnius".to_string(), population: 2718000, region: "Europe".to_string(), languages: vec!["Lithuanian".to_string()] },
        Country { name: "Luxembourg".to_string(), capital: "Luxembourg".to_string(), population: 654000, region: "Europe".to_string(), languages: vec!["Luxembourgish".to_string(), "French".to_string(), "German".to_string()] },
        Country { name: "Malta".to_string(), capital: "Valletta".to_string(), population: 535000, region: "Europe".to_string(), languages: vec!["Maltese".to_string(), "English".to_string()] },
        Country { name: "Moldova".to_string(), capital: "Chișinău".to_string(), population: 2512000, region: "Europe".to_string(), languages: vec!["Romanian".to_string()] },
        Country { name: "Monaco".to_string(), capital: "Monaco".to_string(), population: 36000, region: "Europe".to_string(), languages: vec!["French".to_string()] },
        Country { name: "Montenegro".to_string(), capital: "Podgorica".to_string(), population: 616000, region: "Europe".to_string(), languages: vec!["Montenegrin".to_string()] },
        Country { name: "Netherlands".to_string(), capital: "Amsterdam".to_string(), population: 17618000, region: "Europe".to_string(), languages: vec!["Dutch".to_string()] },
        Country { name: "North Macedonia".to_string(), capital: "Skopje".to_string(), population: 2085000, region: "Europe".to_string(), languages: vec!["Macedonian".to_string()] },
        Country { name: "Norway".to_string(), capital: "Oslo".to_string(), population: 5488000, region: "Europe".to_string(), languages: vec!["Norwegian".to_string()] },
        Country { name: "Poland".to_string(), capital: "Warsaw".to_string(), population: 36822000, region: "Europe".to_string(), languages: vec!["Polish".to_string()] },
        Country { name: "Portugal".to_string(), capital: "Lisbon".to_string(), population: 10467000, region: "Europe".to_string(), languages: vec!["Portuguese".to_string()] },
        Country { name: "Romania".to_string(), capital: "Bucharest".to_string(), population: 19054000, region: "Europe".to_string(), languages: vec!["Romanian".to_string()] },
        Country { name: "Russia".to_string(), capital: "Moscow".to_string(), population: 144444000, region: "Europe".to_string(), languages: vec!["Russian".to_string()] },
        Country { name: "San Marino".to_string(), capital: "San Marino".to_string(), population: 34000, region: "Europe".to_string(), languages: vec!["Italian".to_string()] },
        Country { name: "Serbia".to_string(), capital: "Belgrade".to_string(), population: 6664000, region: "Europe".to_string(), languages: vec!["Serbian".to_string()] },
        Country { name: "Slovakia".to_string(), capital: "Bratislava".to_string(), population: 5426000, region: "Europe".to_string(), languages: vec!["Slovak".to_string()] },
        Country { name: "Slovenia".to_string(), capital: "Ljubljana".to_string(), population: 2119000, region: "Europe".to_string(), languages: vec!["Slovenian".to_string()] },
        Country { name: "Spain".to_string(), capital: "Madrid".to_string(), population: 47616000, region: "Europe".to_string(), languages: vec!["Spanish".to_string()] },
        Country { name: "Sweden".to_string(), capital: "Stockholm".to_string(), population: 10521000, region: "Europe".to_string(), languages: vec!["Swedish".to_string()] },
        Country { name: "Switzerland".to_string(), capital: "Bern".to_string(), population: 8796000, region: "Europe".to_string(), languages: vec!["German".to_string(), "French".to_string(), "Italian".to_string(), "Romansh".to_string()] },
        Country { name: "Ukraine".to_string(), capital: "Kyiv".to_string(), population: 36745000, region: "Europe".to_string(), languages: vec!["Ukrainian".to_string()] },
        Country { name: "United Kingdom".to_string(), capital: "London".to_string(), population: 67736000, region: "Europe".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Vatican City".to_string(), capital: "Vatican City".to_string(), population: 825, region: "Europe".to_string(), languages: vec!["Italian".to_string(), "Latin".to_string()] },
        Country { name: "Australia".to_string(), capital: "Canberra".to_string(), population: 26439000, region: "Oceania".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Fiji".to_string(), capital: "Suva".to_string(), population: 929000, region: "Oceania".to_string(), languages: vec!["English".to_string(), "Fijian".to_string(), "Hindi".to_string()] },
        Country { name: "Kiribati".to_string(), capital: "Tarawa".to_string(), population: 131000, region: "Oceania".to_string(), languages: vec!["English".to_string(), "Gilbertese".to_string()] },
        Country { name: "Marshall Islands".to_string(), capital: "Majuro".to_string(), population: 42000, region: "Oceania".to_string(), languages: vec!["Marshallese".to_string(), "English".to_string()] },
        Country { name: "Micronesia".to_string(), capital: "Palikir".to_string(), population: 115000, region: "Oceania".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Nauru".to_string(), capital: "Yaren".to_string(), population: 13000, region: "Oceania".to_string(), languages: vec!["Nauruan".to_string(), "English".to_string()] },
        Country { name: "New Zealand".to_string(), capital: "Wellington".to_string(), population: 5228000, region: "Oceania".to_string(), languages: vec!["English".to_string(), "Māori".to_string()] },
        Country { name: "Palau".to_string(), capital: "Ngerulmud".to_string(), population: 18000, region: "Oceania".to_string(), languages: vec!["Palauan".to_string(), "English".to_string()] },
        Country { name: "Papua New Guinea".to_string(), capital: "Port Moresby".to_string(), population: 10142000, region: "Oceania".to_string(), languages: vec!["English".to_string(), "Tok Pisin".to_string(), "Hiri Motu".to_string()] },
        Country { name: "Samoa".to_string(), capital: "Apia".to_string(), population: 222000, region: "Oceania".to_string(), languages: vec!["Samoan".to_string(), "English".to_string()] },
        Country { name: "Solomon Islands".to_string(), capital: "Honiara".to_string(), population: 724000, region: "Oceania".to_string(), languages: vec!["English".to_string()] },
        Country { name: "Tonga".to_string(), capital: "Nuku'alofa".to_string(), population: 107000, region: "Oceania".to_string(), languages: vec!["Tongan".to_string(), "English".to_string()] },
        Country { name: "Tuvalu".to_string(), capital: "Funafuti".to_string(), population: 12000, region: "Oceania".to_string(), languages: vec!["Tuvaluan".to_string(), "English".to_string()] },
        Country { name: "Vanuatu".to_string(), capital: "Port Vila".to_string(), population: 327000, region: "Oceania".to_string(), languages: vec!["Bislama".to_string(), "English".to_string(), "French".to_string()] },
    ]
}
