// Mocks generated by Mockito 5.4.6 from annotations
// in bird_watching_mobile/test/blocs/observation_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bird_watching_mobile/data/models/observation.dart' as _i2;
import 'package:bird_watching_mobile/data/repositories/observation_repository.dart'
    as _i3;
import 'package:bird_watching_mobile/data/services/connectivity_service.dart'
    as _i5;
import 'package:connectivity_plus/connectivity_plus.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeObservation_0 extends _i1.SmartFake implements _i2.Observation {
  _FakeObservation_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ObservationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockObservationRepository extends _i1.Mock
    implements _i3.ObservationRepository {
  MockObservationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Observation>> getObservations({
    bool? forceRefresh = false,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getObservations, [], {
              #forceRefresh: forceRefresh,
              #userId: userId,
            }),
            returnValue: _i4.Future<List<_i2.Observation>>.value(
              <_i2.Observation>[],
            ),
          )
          as _i4.Future<List<_i2.Observation>>);

  @override
  _i4.Future<_i2.Observation?> getObservationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getObservationById, [id]),
            returnValue: _i4.Future<_i2.Observation?>.value(),
          )
          as _i4.Future<_i2.Observation?>);

  @override
  _i4.Future<_i2.Observation> createObservation(_i2.Observation? observation) =>
      (super.noSuchMethod(
            Invocation.method(#createObservation, [observation]),
            returnValue: _i4.Future<_i2.Observation>.value(
              _FakeObservation_0(
                this,
                Invocation.method(#createObservation, [observation]),
              ),
            ),
          )
          as _i4.Future<_i2.Observation>);

  @override
  _i4.Future<_i2.Observation> updateObservation(_i2.Observation? observation) =>
      (super.noSuchMethod(
            Invocation.method(#updateObservation, [observation]),
            returnValue: _i4.Future<_i2.Observation>.value(
              _FakeObservation_0(
                this,
                Invocation.method(#updateObservation, [observation]),
              ),
            ),
          )
          as _i4.Future<_i2.Observation>);

  @override
  _i4.Future<void> deleteObservation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteObservation, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Observation>> getPendingSyncObservations() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncObservations, []),
            returnValue: _i4.Future<List<_i2.Observation>>.value(
              <_i2.Observation>[],
            ),
          )
          as _i4.Future<List<_i2.Observation>>);

  @override
  _i4.Future<void> syncObservation(_i2.Observation? observation) =>
      (super.noSuchMethod(
            Invocation.method(#syncObservation, [observation]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Observation>> searchObservations(
    String? query, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchObservations, [query], {#userId: userId}),
            returnValue: _i4.Future<List<_i2.Observation>>.value(
              <_i2.Observation>[],
            ),
          )
          as _i4.Future<List<_i2.Observation>>);

  @override
  _i4.Future<List<_i2.Observation>> filterByDateRange(
    DateTime? startDate,
    DateTime? endDate, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #filterByDateRange,
              [startDate, endDate],
              {#userId: userId},
            ),
            returnValue: _i4.Future<List<_i2.Observation>>.value(
              <_i2.Observation>[],
            ),
          )
          as _i4.Future<List<_i2.Observation>>);

  @override
  _i4.Future<List<_i2.Observation>> getSharedObservations({
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedObservations, [], {
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i4.Future<List<_i2.Observation>>.value(
              <_i2.Observation>[],
            ),
          )
          as _i4.Future<List<_i2.Observation>>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i5.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  _i4.Future<bool> isConnected() =>
      (super.noSuchMethod(
            Invocation.method(#isConnected, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasInternetAccess() =>
      (super.noSuchMethod(
            Invocation.method(#hasInternetAccess, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i6.ConnectivityResult> getConnectivityType() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectivityType, []),
            returnValue: _i4.Future<_i6.ConnectivityResult>.value(
              _i6.ConnectivityResult.bluetooth,
            ),
          )
          as _i4.Future<_i6.ConnectivityResult>);

  @override
  _i4.Future<bool> isWifiConnected() =>
      (super.noSuchMethod(
            Invocation.method(#isWifiConnected, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isMobileConnected() =>
      (super.noSuchMethod(
            Invocation.method(#isMobileConnected, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
