// Mocks generated by Mockito 5.4.6 from annotations
// in bird_watching_mobile/test/blocs/sync_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bird_watching_mobile/data/models/observation.dart' as _i5;
import 'package:bird_watching_mobile/data/models/sync_result.dart' as _i2;
import 'package:bird_watching_mobile/data/services/sync_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i3.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i3.SyncProgress> get syncProgressStream =>
      (super.noSuchMethod(
            Invocation.getter(#syncProgressStream),
            returnValue: _i4.Stream<_i3.SyncProgress>.empty(),
          )
          as _i4.Stream<_i3.SyncProgress>);

  @override
  bool get isSyncing =>
      (super.noSuchMethod(Invocation.getter(#isSyncing), returnValue: false)
          as bool);

  @override
  bool get autoSyncEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#autoSyncEnabled),
            returnValue: false,
          )
          as bool);

  @override
  set autoSyncEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.setter(#autoSyncEnabled, enabled),
    returnValueForMissingStub: null,
  );

  @override
  void startAutoSync() => super.noSuchMethod(
    Invocation.method(#startAutoSync, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopAutoSync() => super.noSuchMethod(
    Invocation.method(#stopAutoSync, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.SyncResult> syncPendingObservations() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingObservations, []),
            returnValue: _i4.Future<_i2.SyncResult>.value(
              _FakeSyncResult_0(
                this,
                Invocation.method(#syncPendingObservations, []),
              ),
            ),
          )
          as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<void> syncObservation(_i5.Observation? observation) =>
      (super.noSuchMethod(
            Invocation.method(#syncObservation, [observation]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
